# Author :  Purvang Lapsiwala

# Let it blank if user want value to be None or Empty

#----------------------------------------------------------------------

# data_preprocessing_config

no_resize : False           # True means no resize op will be performed on image
is_square_resize : True     # square resizing or resizing based on smaller side scale
image_min_side : 500        # min side(height) in pixels
image_max_side : 500        # max side(width) in pixels
random_transform : True     # apply transformation or not

#----------------------------------------------------------------------

# Feature_Extractor_config
backbone: "resnet50"        # ['resnet', 'vgg', 'inception', 'xception', 'efficientnet']
freeze_backbone : False     # whether to update weight of backbone
imagenet_weights : True     # initialize backbone with imagenet weights
#weights : "/Users/purvang/Downloads/resnet50_coco_best_v2.1.0.h5"
no_weights :                # no weight initialization

#----------------------------------------------------------------------
# This configuations will change based on application. whether need more accurate network or need fast inference
# along with choice of backbone.

# Feature_Fusion_config
need_fpn_functionality : True  # need fpn or not. if False, no feature fusion will take place.
fpn_method : "bifpn"           # ["fpn", "bottom_up_fpn", "top_down_fpn", "bifpn", "wbifpn"]
width: 64                      # number of channels in head
depth: 1                       # depth for head
separable_conv : True          # whether to use seperable conv or regular convoluation
freeze_bn : False              # freeze bachnorm
fpn_depth: 1                   # depth of fpn

#----------------------------------------------------------------------

# Anchor_Generation_config
anchor_generation_method : multiple # ["multiple", "flexible"]
sizes   : [32, 64, 128, 256, 512]
strides : [8, 16, 32, 64, 128]
ratios  : [0.5, 1, 2]
scales  : [1.0, 1.26, 1.58]
#config : "./config.ini"

#anchor_generation_method : flexible # ["multiple", "flexible"]
#config :



#----------------------------------------------------------------------

#train_input_config
annotations: "/Users/purvang/Desktop/retinanet/train.csv"
classes : "/Users/purvang/Desktop/retinanet/labels.csv"
val_annotations : "/Users/purvang/Desktop/retinanet/small_test.csv"

tensorboard_dir : "/Users/purvang/Documents/models/keras-retinanet/everest_data/tensorboard/"

snapshot :
snapshot_path :
snapshots :

# train_config
batch_size : 1             # bacth size
initial_epoch : 0          # initial_epoch to start training
epochs : 1                 # number of epochs to run
steps : 1                  # number of steps per epochs (num_images / batch_size)
compute_val_loss : False   # whether to compute validation
reduce_lr_patience : 3     # if defined metric does not improve for these many epoch, reduce lr
reduce_lr_factor : 0.01    # factor by which lr will be reduced
no_evaluation : True       # evaluation for coco dataset
weighted_average : False   # Do we want to compute weighted average of metric performance

#----------------------------------------------------------------------
# lr_config
# if not step or polynomial, lr will be set as "constant" and will be reduced based on reduce_lr_patience.

lr_schedule_method : "constant"
lr : 0.0001

#lr_schedule_method : "step"
#init_lr : 0.01
#factor : 0.25
#dropEveryEpochs : 10

#lr_schedule_method : "polynomial"
#maxEpochs : 100
#initAlpha : 0.01
#power : 1.0

#----------------------------------------------------------------------

# Feature_Visualization_config
image_path: "./features/1.jpeg"  # (image path whose feature maps are interested .)
conv_features : False            # (save featuremaps after conv op)
bn_features : False              # (save features maps batch norn op)
activation_features : False      # (save features maps batch activation op)
save_weights : False             # (whether we want to save weight related to corresponding op)
feature_freq_in_epochs: 1        # (epochs after we want to save feature maps)
feature_saving_dir_path : "./features"  # (feature maps saving parent dir)
num_of_channels : 1    # (number of channels to save for feature map.)
#----------------------------------------------------------------------


gpu : 0
multi_gpu : 0
multi_gpu_force : False

multiprocessing: False
workers : 0
max_queue_size : 10
